# Generated by Django 3.0.6 on 2020-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default-pic.jpg', upload_to='category_pics'),
        ),
    ]
