# Generated by Django 3.0.6 on 2020-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200716_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default-cat.jpg', upload_to='category_pics'),
        ),
    ]
